[build-system]
requires = ["setuptools<81", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version" # exclude "+<hash>" from version name so we can upload to Test PyPI

[project]
name = "simulaqron"
dynamic = ["version"]
dependencies = [
    "dataclasses-serialization>=1.3.1, <2.0",
    "numpy>=1.14.0,<2.0.0",
    "dill>=0.4.0,<1.0.0",
    "scipy>=1.1.0,<2.0.0",
    "twisted>=24.0.0,<26.0.0",
    "networkx>=3.0,<3.6",
    "click>=8.0,<9.0",
    "daemons>=1.3.0,<2.0.0",
    "netqasm>=2.1.1,<3.0.0",
    "multiprocess>=0.70.18,<1.0",
    "StrEnum<1.0.0"
]
requires-python = ">=3.10,<3.13"
authors = [
  {name = "Axel Dahlberg", email = "e.a.dahlberg@tudelft.nl"}
]
maintainers = [
  {name = "Diego Rivera", email = "d.a.g.a.rivera@tudelft.nl"}
]
description = "A simulator for developing Quantum Internet software"
readme = "README.md"
keywords = ["simulaqron", "quantum simulator", "quantum application", "qubit", "tudelft"]
classifiers = [
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: Unix",
        "Operating System :: MacOS"
]

[project.optional-dependencies]
opt = [
    "projectq<=0.8.0",
    "qutip<5.0.0"
]
dev = [
    "flake8>=5.0.0,<6.0.0",
    "pytest>=7.1, <8.0",
    "qutip<5.0.0",
    "sphinx>=7.2.6, <8.0",
    "sphinx-rtd-theme",
    "build",
    "twine",
    "pylint",
    "pyink",
    "pytest>=7.1, <8.0",
    "mypy",
]

[tool.setuptools.packages.find]
include = ["simulaqron"]
exclude = ["simulaqron/config"]

[project.scripts]
simulaqron = "simulaqron.cli:cli_entry_point"

[project.urls]
Homepage = "https://github.com/SoftwareQuTech/SimulaQron"
Documentation = "https://softwarequtech.github.io/SimulaQron/index.html"
Changelog = "https://github.com/SoftwareQuTech/SimulaQron/blob/master/CHANGELOG.md"
Repository = "https://github.com/SoftwareQuTech/SimulaQron"
