name: General check

on: push

jobs:
  lint:
    name: Run linter  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: "3.12"
    - run: |
        make lint-deps
        make lint

  tests-examples:
    name: Run tests and examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: "3.12"
    - run: |
        make test-deps
        make tests
        make examples
