name: Slow tests

on: push

jobs:
  slow-tests:
    name: Run slow tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: "3.12"
    - name: Install simulaqron
      run: make install
    - name: Run slow tests
      run: make tests_slow
